---
- name: "Install Prometheus from binary"
  ansible.builtin.include_tasks: install.yml

- name: "Configure and add alert rules"
  ansible.builtin.include_tasks: configure.yml

- name: "Flush handlers"
  ansible.builtin.meta: "flush_handlers"
