---
- name: Converge
  hosts: all

  pre_tasks:
    - name: "Create Prometheus system group"
      ansible.builtin.group:
        name: prometheus
        system: true
        state: present

    - name: "Create Prometheus system user"
      ansible.builtin.user:
        name: prometheus
        group: prometheus
        system: true
        shell: "/sbin/nologin"
        create_home: false
        state: present

  roles:
    - role: genlab.prometheus
      config_source_dir: molecule/default
