---
global:
  scrape_interval: 15s
  evaluation_interval: 15s


# Rules and alerts are read from the specified file(s)
rule_files:
  - "/etc/prometheus/alert-rules.yaml"


alerting:
  alertmanagers:
    - static_configs:
        - targets: [ 'localhost:9093' ]


scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: "node-exporter"
    static_configs:
      - targets: [ "localhost:9100" ]